name: cxon benchmarks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  gnuplot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workflows-data
      uses: actions/checkout@v3
    - name: gnuplot setup
      run: |
        sudo apt-get update
        sudo apt-get install gnuplot
    - name: Generate
      run: |
        cd cxon/benchmarks
        src/plot-all.sh
    - name: Commit
      run: |
        cd cxon/benchmarks
        if [[ `git status --porcelain` ]]; then
          git config user.name "oknenavin" && git config user.email ${{ secrets.CXON_MAIL }}
          git pull
          git add . && git commit -am "|${{ github.event.head_commit.message }}"
          git push
        fi
